on: workflow_dispatch
jobs:
  debian:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        debian_release: [bullseye]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - run: |
          TAG=${{ matrix.debian_release }}
          UPSTREAM=$(git describe --tags --always --dirty)
          BUILD_TIME="$(date +%FT%T%z)"
          echo "UPSTREAM=${UPSTREAM#v}" >> $GITHUB_ENV
          echo "BUILD_TIME=$BUILD_TIME" >> $GITHUB_ENV
          echo "REACT_APP_BUILD_VERSION=$UPSTREAM-$BUILD_TIME" >> $GITHUB_ENV
          echo "BUILD_VERSION=1:$UPSTREAM-$TAG" >> $GITHUB_ENV
      - run: |
          echo $BUILD_TIME
          echo $REACT_APP_BUILD_VERSION
          echo $BUILD_VERSION
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.debian_release }}
          path: ./target/*.deb
